ChatSignalRAzurePost/Models/ChatPost.cs
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace ChatSignalRAzurePost.Models
{
    [Table("CHAT_POST")]
    public class ChatPost
    {
        [Key]
        [Column("ID")]
        public int Id { get; set; }
        [Column("MESSAGE")]
        public string Message { get; set; }
        [Column("SENDER")]
        public string Sender { get; set; }
    }
}

ChatSignalRAzurePost/Models/ErrorViewModel.cs
namespace ChatSignalRAzurePost.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ChatSignalRAzurePost/Controllers/ChatPostsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ChatSignalRAzurePost.Data;
using ChatSignalRAzurePost.Models;

namespace ChatSignalRAzurePost.Controllers
{
    public class ChatPostsController : Controller
    {
        private readonly ChatContext _context;

        public ChatPostsController(ChatContext context)
        {
            _context = context;
        }

        // GET: ChatPosts
        public async Task<IActionResult> Index()
        {
            return _context.ChatPosts != null ?
                        View(await _context.ChatPosts.OrderByDescending(x => x.Id).ToListAsync()) :
                        Problem("Entity set 'ChatContext.ChatPosts'  is null.");
        }

        // GET: ChatPosts/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.ChatPosts == null)
            {
                return NotFound();
            }

            var chatPost = await _context.ChatPosts
                .FirstOrDefaultAsync(m => m.Id == id);
            if (chatPost == null)
            {
                return NotFound();
            }

            return View(chatPost);
        }

        private async Task<int> GetMaxChatPostAsync()
        {
            int maxId = 1;

            if (await _context.ChatPosts.AnyAsync())
            {
                maxId = await this._context.ChatPosts.MaxAsync(x => x.Id) + 1;
            }

            return maxId;
        }

        // POST: ChatPosts/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(string message, string sender)
        {
            if (ModelState.IsValid)
            {
                ChatPost chatPost = new()
                {
                    Id = await GetMaxChatPostAsync(),
                    Message = message,
                    Sender = sender
                };

                await _context.ChatPosts.AddAsync(chatPost);
                await _context.SaveChangesAsync();
            }
            return RedirectToAction(nameof(Index));
        }

        // GET: ChatPosts/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.ChatPosts == null)
            {
                return NotFound();
            }

            var chatPost = await _context.ChatPosts.FindAsync(id);
            if (chatPost == null)
            {
                return NotFound();
            }
            return View(chatPost);
        }

        // POST: ChatPosts/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Message,Sender")] ChatPost chatPost)
        {
            if (id != chatPost.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(chatPost);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ChatPostExists(chatPost.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(chatPost);
        }

        // GET: ChatPosts/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.ChatPosts == null)
            {
                return NotFound();
            }

            var chatPost = await _context.ChatPosts
                .FirstOrDefaultAsync(m => m.Id == id);
            if (chatPost == null)
            {
                return NotFound();
            }

            return View(chatPost);
        }

        // POST: ChatPosts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.ChatPosts == null)
            {
                return Problem("Entity set 'ChatContext.ChatPosts'  is null.");
            }
            var chatPost = await _context.ChatPosts.FindAsync(id);
            if (chatPost != null)
            {
                _context.ChatPosts.Remove(chatPost);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ChatPostExists(int id)
        {
            return (_context.ChatPosts?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

ChatSignalRAzurePost/Controllers/HomeController.cs
using ChatSignalRAzurePost.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace ChatSignalRAzurePost.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ChatSignalRAzurePost/Views/ChatPosts/Delete.cshtml
@model ChatSignalRAzurePost.Models.ChatPost

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ChatPost</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Message)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Message)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Sender)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Sender)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

ChatSignalRAzurePost/Views/ChatPosts/Details.cshtml
@model ChatSignalRAzurePost.Models.ChatPost

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>ChatPost</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Message)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Message)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Sender)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Sender)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

ChatSignalRAzurePost/Views/ChatPosts/Edit.cshtml
@model ChatSignalRAzurePost.Models.ChatPost

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>ChatPost</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Message" class="control-label"></label>
                <input asp-for="Message" class="form-control" />
                <span asp-validation-for="Message" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Sender" class="control-label"></label>
                <input asp-for="Sender" class="form-control" />
                <span asp-validation-for="Sender" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ChatSignalRAzurePost/Views/ChatPosts/Index.cshtml
@model IEnumerable<ChatSignalRAzurePost.Models.ChatPost>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div class="form-group">
                <label class="control-label">Message</label>
                <input name="Message" id="messageInput" class="form-control" required />
            </div>
            <div class="form-group">
                <label class="control-label">Sender</label>
                <input name="Sender" id="userInput" class="form-control" required />
            </div>
            <div class="form-group">
                <button id="sendButton" type="submit" value="Create" class="btn btn-primary">
                    Send message
                </button>
            </div>
        </form>
    </div>
</div>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Message)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Sender)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody id="messagesList">
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Message)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Sender)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>

@section Scripts {
    <script src="~/js/chat.js" asp-append-version="true"></script>
}

ChatSignalRAzurePost/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

ChatSignalRAzurePost/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ChatSignalRAzurePost</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ChatSignalRAzurePost.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ChatSignalRAzurePost</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ChatPosts" asp-action="Index">Chat</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - ChatSignalRAzurePost - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/lib/signalr/dist/browser/signalr.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>